package com.bw.movie.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;
import com.bw.movie.bean.LoginSubBean;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginSubBeanDaoConfig;

    private final LoginSubBeanDao loginSubBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginSubBeanDaoConfig = daoConfigMap.get(LoginSubBeanDao.class).clone();
        loginSubBeanDaoConfig.initIdentityScope(type);

        loginSubBeanDao = new LoginSubBeanDao(loginSubBeanDaoConfig, this);

        registerDao(LoginSubBean.class, loginSubBeanDao);
    }
    
    public void clear() {
        loginSubBeanDaoConfig.clearIdentityScope();
    }

    public LoginSubBeanDao getLoginSubBeanDao() {
        return loginSubBeanDao;
    }

}
